# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zVHw4FuNGvxTm6FsqIzVXEW6uYzEhwYN
"""

import pandas as pd

train = pd.read_csv("train_processed.csv")
test = pd.read_csv("test_processed.csv")

X_train = train.drop(columns=["good_quality"])
y_train = train["good_quality"]

X_test = test.drop(columns=["good_quality"])
y_test = test["good_quality"]

print(X_train.shape)
print(y_train.value_counts())

sample_weight = train["sample_weight"]

X_train = train.drop(columns=["good_quality", "sample_weight"])
y_train = train["good_quality"]

X_test = test.drop(columns=["good_quality"])
y_test = test["good_quality"]

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train, sample_weight=sample_weight)

y_pred_lr = lr.predict(X_test)
y_prob_lr = lr.predict_proba(X_test)[:, 1]

from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

print("Logistic Regression Results")
print(classification_report(y_test, y_pred_lr))
print("ROC-AUC:", roc_auc_score(y_test, y_prob_lr))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr))

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=6,
    class_weight="balanced",
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)
y_prob_rf = rf.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred_rf))
print("ROC-AUC:", roc_auc_score(y_test, y_prob_rf))

from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    scale_pos_weight=6,
    random_state=42
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)
y_prob_xgb = xgb.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred_xgb))
print("ROC-AUC:", roc_auc_score(y_test, y_prob_xgb))

from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    rf, X_train, y_train,
    cv=5,
    scoring="f1"
)

print("RF CV F1:", cv_scores.mean())

from sklearn.model_selection import GridSearchCV

param_grid = {
    "max_depth": [3, 4, 5],
    "n_estimators": [100, 200]
}

grid = GridSearchCV(
    XGBClassifier(),
    param_grid,
    cv=3,
    scoring="f1"
)

grid.fit(X_train, y_train)

print(grid.best_params_)

from xgboost import XGBClassifier

xgb_best = XGBClassifier(
    max_depth=4,
    n_estimators=200,
    learning_rate=0.05,
    scale_pos_weight=6,
    random_state=42
)

xgb_best.fit(X_train, y_train)

y_pred_best = xgb_best.predict(X_test)
y_prob_best = xgb_best.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred_best))
print("ROC-AUC:", roc_auc_score(y_test, y_prob_best))

cv_scores_xgb = cross_val_score(
    xgb, X_train, y_train,
    cv=5,
    scoring="f1"
)

print("XGB CV F1:", cv_scores_xgb.mean())

# Logistic
cm_lr = confusion_matrix(y_test, y_pred_lr)
sns.heatmap(cm_lr, annot=True, fmt="d", cmap="Blues")
plt.title("Logistic Regression")
plt.show()

# Random Forest
cm_rf = confusion_matrix(y_test, y_pred_rf)
sns.heatmap(cm_rf, annot=True, fmt="d", cmap="Blues")
plt.title("Random Forest")
plt.show()

# XGBoost
cm_xgb = confusion_matrix(y_test, y_pred_best)
sns.heatmap(cm_xgb, annot=True, fmt="d", cmap="Blues")
plt.title("XGBoost")
plt.show()